# exp_config.yaml

# Environmental settings
process_settings:
  num_gpus: 1
  specify_gpus: "0"
  master_port: 8299
  multi_node_settings:
    enable: False
    master_addr: "127.0.0.1"

# Running train, eval, inference related settings
run_settings:
  task_type: "text-generation"
  task_mode: "train"
  per_device_train_batch_size: 2
  per_update_total_batch_size: 20
  num_train_epochs: 1
  max_iter: -1
  max_seq_len: 4096
  triton: True
  weight_file_format: null
  from_config: false
  precision_mode: 1
  enable_save_optimizer_state: false

  model_saver:
    max_num_of_saved_model_on_epoch_end: -1  # If -1, equals num_train_epochs
    enable_save_model_on_iteration: false
    max_num_of_saved_model_on_iteration: 2
    num_of_iteration_to_save_model: 2

  lr_scheduler:
    mode: 1
    learning_rate: 0.000007

  optimizer:
    beta1: 0.9
    beta2: 0.95
    eps: 0.00000001
    weight_decay: 0.01

  early_stop:
    enable: false
    min_delta: 0.01
    patience: 2
    verbose: false

  lora:
    enable_lora: false
    lora_rank: 8
    lora_alpha: 16
    lora_task_type: "CAUSAL_LM"
    lora_target_modules: null
